name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Java
      uses: actions/setup-java@v3  # Updated to the latest version
      with:
        java-version: '17'
        distribution: 'zulu'  # Specify the JDK distribution

    - name: Build with Maven
      run: mvn clean package

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "target/hello-backend-0.0.1-SNAPSHOT.jar"
        target: "/home/azureuser/"

    - name: Execute SSH command
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo pkill -f 'java -jar'
          sudo nohup java -jar /home/azureuser/hello-backend-0.0.1-SNAPSHOT.jar &
